### ISSUE TITLE
CounterBore Problem on Bottom of Spoil Board

### ISSUE THREAD

**Issue by ldkraemer** [twforeman/g-code-generators#1]
I want to make a Spoil Board that is 32" x 32" and I want a matrix of 15 x 15 holes for 1/4" x 20 Thread Inserts.
The holes must be 23/64 and extend all way through the 5/8 or 3/4 MDF Board.  I need to counter Bore the
Base of the Spoil Board (top when I am creating it on the CNC Mill) so it is counter bored .050 deep and .5" in
Diameter.

In trying your Python code and selecting the counter bore, your code also counter bores the bottom side in
the Simulator I tested it in.  (Actually that becomes the top of the spoil board, but enlarges the hole in the spoil
board making it not work.

Will you change your code so the Counter Bore ONLY works on the First surface the End Mill works on?

Thanks.  It will work perfect after that for my purpose.

Larry Kraemer

/home/larry/Pictures/Counterbore.png
![Counterbore](https://user-images.githubusercontent.com/36509186/107692145-015ee580-6c72-11eb-8036-23423475614e.png)

**Comment by twforeman** [comment]
Unfortunately the python version is incomplete. Since I haven't touched this code since 2013, and I'm not really a python developer, I'm going to delete the python version.

The Perl version should work - I use it all the time.
